### PR TITLE
Update VS projects

### PR DESCRIPTION
**Pull request by eugeneopalev**
Changes summary:
- Merge libogg_static.sln and libogg_dynamic.sln solution files into single libogg.sln
- Create proper configurations for DLL builds (DebugDLL and ReleaseDLL)
- Also create same solutions for VS2017 and VS2019

Now you can build libogg on Windows out of the box without any problems.

### CODE REVIEW

**Comment by rillian** [comment]
Wow, thanks for all the work!

I don't use Visual Studio, so a couple of quick questions to better understand your intent here:

1. We have cmake support now, which some people say is their preferred way of building unix packages for Windows. Do we still need project files?

2. Visual Studio can generally open older project files. What's the advantage of maintaining three sets of project files? Can they all be tested on appveyor?

**Comment by willson-chen** [comment]
@rillian agree with your opinion. CMake is a better way, while win32 folder is out of date. Why not consider about removing win32 folder?

**Comment by eugeneopalev** [comment]
@rillian Maintaining three project files is a little too much, I agree. They basically all the same. Should I just leave VS2015 project or remove win32 folder completely and rely on CMake? I think the second variant is more preferable.

**Comment by rillian** [comment]
Ok great. How about:

- For this PR, just leave the VS2015 project file. I'll merge that for the
1.3.4 release next week.
- Prepare another PR which removes the win32 folder entirely. I'll merge
that after 1.3.4 is out.

That way there's at least one release where the Visual Studio project files
are marked deprecated.

Sound reasonable?

**Comment by willson-chen** [comment]
> Ok great. How about: 
> 
>\- For this PR, just leave the VS2015 project file. I'll merge that for the 1.3.4 release next week. 
> \- Prepare another PR which removes the win32 folder entirely. I'll merge that after 1.3.4 is out.
>
>That way there's at least one release where the Visual Studio project files are marked deprecated. 
>
>Sound reasonable?

Agree. It is a reasonable way of leaving some time for vs develops who use win32 to transfer to cmake,

**Comment by eugeneopalev** [comment]
@rillian Removed VS2017 and VS2019 projects. Also removed DLL configurations from appveyor.yml. Don't think that setup complex build matrix with DLLs for VS project is a good idea if it will be removed anyway.

**Comment by rillian** [comment]
I've rebased and and pushed as 6d55ddf64b65227409c1e13039aa1f9c13a921b2. Thanks for the cleanup!

**Pull request closed without merging**
